7831.main - Multistep Form
KuzyaWkk/DDEV-test pull request #72
Opened 2024-04-22 06:31 UTC by KuzyaWkk

https://redmine.devbranch.work/issues/7831

Created an element multistep ui table that extends the table. 
Created a multistep form for ordering a product. 
Also created a configuration form that allows you to swap steps and disable certain steps.
Two different configuration forms have been created, one of which uses the multistep ui table element renderer. 
The other form provides similar functionality but with a crutch, without its own js.
Added js for the configuration form with multistep ui table using JQuery.

2024-04-22 06:44 UTC, faust174 approved these changes
LGTM

2024-04-29 09:25 UTC, lavrenchuk-dev requested changes
Overall looks okay, but didn't review JS properly, at first glance it seems like some parts in that JS are not usefull

2024-04-29 09:25 UTC, lavrenchuk-dev commented on web/modules/custom/multistep_form/src/Form/MultistepForm.php
> +      $form['text'] = [
I think better will be to move this to access handler
If no steps is available user shouldn't be able to access the form

2024-04-29 09:25 UTC, lavrenchuk-dev commented on web/modules/custom/multistep_form/src/Form/MultistepForm.php
> +    ];
Are users without access to the settings will be able to see that?

2024-05-01 09:58 UTC, lavrenchuk-dev approved these changes

2024-05-01 09:59 UTC, merged